# URL_SERVER = 'test.rebex.net'
# URL_SERVER = 'ftp.gnu.org'
# URL_SERVER = 'ftp.pureftpd.org'
URL_SERVER = 'ftp.vim.org'
# URL_SERVER = 'ftp.slackware.com'
# URL_SERVER = 'n1.hostedftp.com'
PORT = 21
CMD_USER = b"USER anonymous\r\n"
CMD_PASS = b"PASS anonymous\r\n"
CMD_PASV = b"PASV\r\n"
CMD_PORT = b"PORT\r\n"
CMD_LIST = b"LIST\r\n"
CMD_QUIT = b"QUIT\r\n"
CMD_CWD = b'CWD'
CMD_PWD = b'PWD\r\n'
CMD_MKD = b'MKD'
CMD_RETR = b'RETR GEMA_ENG.TXT\r\n'
CMD_STOR = b'STOR'
